name: Lint check

on: push

jobs:
  lint-check:
    runs-on: ubuntu-latest
    steps:
      - uses: glzr-io/actions/setup-pnpm@main
        with:
          checkout: true
          node-version: 22

      - run: pnpm lint
